# Generated by Django 6.0.1 on 2026-02-03 12:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoundItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Provide a detailed description of the found item')),
                ('category', models.CharField(choices=[('BAG', 'Bag/Backpack'), ('PHONE', 'Phone/Mobile Device'), ('WALLET', 'Wallet/Purse'), ('KEYS', 'Keys'), ('LAPTOP', 'Laptop/Computer'), ('CLOTHING', 'Clothing'), ('JEWELRY', 'Jewelry/Watch'), ('DOCUMENTS', 'Documents/ID'), ('ELECTRONICS', 'Electronics'), ('GLASSES', 'Glasses/Sunglasses'), ('HEADPHONES', 'Headphones/Earbuds'), ('UMBRELLA', 'Umbrella'), ('BOOKS', 'Books/Stationery'), ('SPORTS', 'Sports Equipment'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('location_found', models.CharField(help_text='Where the item was found', max_length=255)),
                ('date_found', models.DateField(help_text='Date when the item was found')),
                ('time_found', models.TimeField(blank=True, help_text='Approximate time when the item was found', null=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('CLAIMED', 'Claimed'), ('RETURNED', 'Returned to Owner')], default='AVAILABLE', max_length=20)),
                ('secret_question', models.CharField(blank=True, help_text='Secret question to verify ownership (e.g., "What\'s inside?")', max_length=255)),
                ('secret_answer_hash', models.CharField(blank=True, help_text='Hashed secret answer', max_length=255)),
                ('embedding_id', models.IntegerField(blank=True, help_text='Reference to FAISS index position', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='found_items/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='found_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Found Item',
                'verbose_name_plural': 'Found Items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LostItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Provide a detailed description of the item')),
                ('category', models.CharField(choices=[('BAG', 'Bag/Backpack'), ('PHONE', 'Phone/Mobile Device'), ('WALLET', 'Wallet/Purse'), ('KEYS', 'Keys'), ('LAPTOP', 'Laptop/Computer'), ('CLOTHING', 'Clothing'), ('JEWELRY', 'Jewelry/Watch'), ('DOCUMENTS', 'Documents/ID'), ('ELECTRONICS', 'Electronics'), ('GLASSES', 'Glasses/Sunglasses'), ('HEADPHONES', 'Headphones/Earbuds'), ('UMBRELLA', 'Umbrella'), ('BOOKS', 'Books/Stationery'), ('SPORTS', 'Sports Equipment'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('location_lost', models.CharField(help_text='Where the item was lost', max_length=255)),
                ('date_lost', models.DateField(help_text='Date when the item was lost')),
                ('time_lost', models.TimeField(blank=True, help_text='Approximate time when the item was lost', null=True)),
                ('status', models.CharField(choices=[('SEARCHING', 'Searching'), ('MATCHED', 'Potential Match Found'), ('CLAIMED', 'Claimed'), ('EXPIRED', 'Expired')], default='SEARCHING', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this item is actively being searched for')),
                ('search_expiry_date', models.DateTimeField(blank=True, help_text='Date when proactive searching expires', null=True)),
                ('embedding_id', models.IntegerField(blank=True, help_text='Reference to FAISS index position', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='lost_items/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lost Item',
                'verbose_name_plural': 'Lost Items',
                'ordering': ['-created_at'],
            },
        ),
    ]
