# Generated by Django 5.2.12 on 2026-05-04 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='founditem',
            name='brand',
            field=models.CharField(blank=True, help_text='Brand of the item (if applicable)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='founditem',
            name='color',
            field=models.CharField(blank=True, help_text='Primary color of the item', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='brand',
            field=models.CharField(blank=True, help_text='Brand of the item (if applicable)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='color',
            field=models.CharField(blank=True, help_text='Primary color of the item', max_length=50, null=True),
        ),
    ]
