# Generated by Django 6.0.1 on 2026-05-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_founditem_brand_founditem_color_lostitem_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='founditem',
            name='secret_answer_raw',
            field=models.CharField(blank=True, help_text='Raw secret answer for semantic matching', max_length=255),
        ),
        migrations.AlterField(
            model_name='founditem',
            name='secret_answer_hash',
            field=models.CharField(blank=True, help_text='Hashed secret answer (Legacy)', max_length=255),
        ),
    ]
