# Generated by Django 5.2.12 on 2026-05-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegram_bot", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="telegramsession",
            name="state",
            field=models.CharField(
                choices=[
                    ("START", "Start"),
                    ("ASK_PHONE", "Ask Phone"),
                    ("ASK_EMAIL", "Ask Email"),
                    ("ASK_PASSWORD", "Ask Password"),
                    ("ASK_TITLE", "Ask Title"),
                    ("ASK_DESCRIPTION", "Ask Description"),
                    ("ASK_CATEGORY", "Ask Category"),
                    ("ASK_LOCATION", "Ask Location"),
                    ("ASK_DATE", "Ask Date"),
                    ("CONFIRM", "Confirm"),
                ],
                default="START",
                max_length=30,
            ),
        ),
    ]
