# Generated by Django 6.0.1 on 2026-02-03 12:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('semantic_score', models.FloatField(default=0.0, help_text='Cosine similarity between text embeddings')),
                ('time_score', models.FloatField(default=0.0, help_text='Time proximity score')),
                ('location_score', models.FloatField(default=0.0, help_text='Location matching score')),
                ('final_score', models.FloatField(default=0.0, help_text='Weighted final score')),
                ('rank', models.IntegerField(default=0, help_text='Ranking among matches for the lost item')),
                ('status', models.CharField(choices=[('POTENTIAL', 'Potential Match'), ('CLAIMED', 'Claim Submitted'), ('VERIFIED', 'Verified & Returned'), ('REJECTED', 'Match Rejected')], default='POTENTIAL', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('found_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='items.founditem')),
                ('lost_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='items.lostitem')),
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Matches',
                'ordering': ['-final_score', '-created_at'],
                'unique_together': {('lost_item', 'found_item')},
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('secret_answer_provided', models.CharField(blank=True, help_text='The answer provided by the claimant', max_length=255)),
                ('is_correct_answer', models.BooleanField(default=False, help_text='Whether the secret answer was correct')),
                ('additional_proof', models.TextField(blank=True, help_text='Additional proof provided by claimant')),
                ('proof_image', models.ImageField(blank=True, help_text='Proof image (e.g., receipt, photo of item)', null=True, upload_to='claim_proofs/')),
                ('admin_notes', models.TextField(blank=True, help_text='Notes from admin review')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PROOF_REQUIRED', 'Additional Proof Required')], default='PENDING', max_length=20)),
                ('attempt_count', models.IntegerField(default=1, help_text='Number of claim attempts by this user')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('claimant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_claims', to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='matching.match')),
            ],
            options={
                'verbose_name': 'Claim',
                'verbose_name_plural': 'Claims',
                'ordering': ['-created_at'],
            },
        ),
    ]
