# Generated by Django 5.2.12 on 2026-05-20 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='metadata_score',
            field=models.FloatField(default=0.0, help_text='Composite metadata similarity (category, location, time, color)'),
        ),
        migrations.AlterField(
            model_name='match',
            name='final_score',
            field=models.FloatField(default=0.0, help_text='Hybrid final score: alpha * semantic + (1-alpha) * metadata'),
        ),
    ]
