# Generated by Django 5.2.12 on 2026-05-20 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=30, unique=True)),
                ('state', models.CharField(choices=[('START', 'Start'), ('ASK_EMAIL', 'Ask Email'), ('ASK_TITLE', 'Ask Title'), ('ASK_DESCRIPTION', 'Ask Description'), ('ASK_CATEGORY', 'Ask Category'), ('ASK_LOCATION', 'Ask Location'), ('ASK_DATE', 'Ask Date'), ('CONFIRM', 'Confirm')], default='START', max_length=30)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
